Tokenized vault
Ithil-protocol/v1-core pull request #197
Opened 2022-10-28 16:05 UTC by lsqrl

2022-10-29 18:48 UTC, OxMarco requested changes

2022-10-29 18:48 UTC, OxMarco commented on contracts/TokenizedVault.sol
> +    constructor(address _token)
`constructor(IERCMetadata _token)`

2022-10-29 18:48 UTC, OxMarco commented on contracts/test/MockTimeTokenizedVault.sol
> +contract MockTimeTokenizedVault is TokenizedVault {
useless, just advance blocktime in the simulation

2022-10-31 08:37 UTC, lsqrl commented on contracts/test/MockTimeTokenizedVault.sol
> +contract MockTimeTokenizedVault is TokenizedVault {
Hardhat tests register timestamps sequentially: if you do an operation and another one immediately after, the timestamp of the second one is in general higher than the previous one. In particular:
- I did not manage to make precise calculation of fees unlocking in the non-mock time vault case: even if I advance the block time, afterwards I need to execute an async operation with `await` and since this takes some time, hardhat advances the timestamps of one second or so thus there is always a tiny error, and it does not seem to be predictable.
- Conversely, I do not know how to enforce hardhat to make many lengthy operations to have the same timestamp (i.e. test what happens with many operations in the same block). If you know how to do that please advise. Anyway this contract is just for testing.

2022-10-31 16:53 UTC, lsqrl commented on contracts/TokenizedVault.sol
> +    constructor(address _token)
Done

2022-11-01 16:22 UTC, merged